package io.github.soulcodingmatt.equilibrium.processor.generation.dto;

import io.github.soulcodingmatt.equilibrium.processor.generation.emit.CodeWriter;
import io.github.soulcodingmatt.equilibrium.processor.generation.emit.GeneratorUtility;
import java.io.IOException;
import java.io.Writer;
import java.util.List;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;

/**
 * Emits a DTO class file given the key pieces of data. This is intentionally minimal at first and
 * will evolve as we progressively extract logic from {@link DtoGenerator}.
 *
 * <p>When {@code useSuperBuilder} is true, Lombok later generates builder implementation types;
 * those may use {@code $} in member names per Lombok, not under Equilibrium’s control.
 */
public final class DtoClassWriter {

  public void writeFileHeader(Writer writer, String packageName, boolean useSuperBuilder)
      throws IOException {
    writer.write("package " + packageName + ";\n\n");
    if (useSuperBuilder) {
      writer.write("import lombok.experimental.SuperBuilder;\n");
    }
    writer.write("import java.util.Objects;\n");
  }

  public void beginClass(
      CodeWriter code, String className, TypeElement sourceType, boolean useSuperBuilder)
      throws IOException {
    code.write("/**\n");
    code.write(" * DTO for {@link " + sourceType.getQualifiedName() + "}\n");
    code.write(" * Generated by Project Equilibrium\n");
    code.write(" */\n");
    if (useSuperBuilder) {
      code.write("@SuperBuilder\n");
    }
    code.beginBlock("public class " + className);
    code.blankLine();
  }

  public void emitGetter(CodeWriter code, String type, String name) throws IOException {
    String cap = name.substring(0, 1).toUpperCase() + name.substring(1);
    code.beginBlock("public " + type + " get" + cap + "()");
    code.writeLine("return this." + name + ";");
    code.endBlock();
    code.blankLine();
  }

  public void emitSetter(CodeWriter code, String type, String name) throws IOException {
    String cap = name.substring(0, 1).toUpperCase() + name.substring(1);
    code.beginBlock("public void set" + cap + "(" + type + " " + name + ")");
    code.writeLine("this." + name + " = " + name + ";");
    code.endBlock();
    code.blankLine();
  }

  public void emitConstructor(
      CodeWriter code,
      String className,
      List<VariableElement> fields,
      java.util.function.Function<VariableElement, String> typeResolver)
      throws IOException {
    StringBuilder header = new StringBuilder("public " + className + "(");
    boolean first = true;
    for (VariableElement f : fields) {
      if (!first) header.append(", ");
      header.append(typeResolver.apply(f)).append(" ").append(f.getSimpleName());
      first = false;
    }
    header.append(")");
    code.beginBlock(header.toString());
    for (VariableElement f : fields) {
      String name = f.getSimpleName().toString();
      code.writeLine("this." + name + " = " + name + ";");
    }
    code.endBlock();
    code.blankLine();
  }

  public void emitEqualsHashToString(
      Writer writer, List<VariableElement> fields, String className, String dtoClassName)
      throws IOException {
    // Defer to GeneratorUtility for consistent behavior
    GeneratorUtility.writeEquals(writer, fields, className);
    GeneratorUtility.writeHashCode(writer, fields);
    GeneratorUtility.writeToString(writer, fields, dtoClassName);
  }
}
