package io.github.soulcodingmatt.equilibrium.processor.generation.record;

import io.github.soulcodingmatt.equilibrium.processor.generation.emit.GeneratorUtility;
import io.github.soulcodingmatt.equilibrium.processor.generation.emit.GeneratorUtility.FieldInclusionConfig;
import io.github.soulcodingmatt.equilibrium.processor.generation.emit.GeneratorUtility.GeneratorType;
import java.io.IOException;
import java.io.Writer;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.annotation.processing.Filer;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.tools.JavaFileObject;

public class RecordGenerator {
  private final TypeElement classElement;
  private final String packageName;
  private final String recordClassName;
  private final Set<String> ignoredFields;
  private final Filer filer;
  private final int recordId;
  private final RecordValidationEmitter validationEmitter;

  public RecordGenerator(
      RecordGeneratorTarget target, Filer filer, RecordValidationEmitter validationEmitter) {
    this.classElement = target.classElement();
    this.packageName = target.packageName();
    this.recordClassName = target.recordClassName();
    this.ignoredFields =
        target.ignoredFields() != null ? new HashSet<>(target.ignoredFields()) : new HashSet<>();
    this.filer = filer;
    this.recordId = target.recordId();
    this.validationEmitter = validationEmitter;
  }

  public void generate() throws IOException {
    // Create field inclusion configuration
    FieldInclusionConfig fieldConfig =
        new FieldInclusionConfig(GeneratorType.RECORD, ignoredFields, recordId);

    // Get all fields that should be included in the Record
    List<VariableElement> fields = GeneratorUtility.getIncludedFields(classElement, fieldConfig);

    // Collect validation imports
    Set<String> validationImports = validationEmitter.collectImports(fields, recordId);

    // Create or update the Record file
    JavaFileObject sourceFile =
        filer.createSourceFile(packageName + "." + recordClassName, classElement);

    try (Writer writer = sourceFile.openWriter()) {
      // Write package declaration
      writer.write("package " + packageName + ";\n\n");

      // Write imports (records typically don't need Objects import for equals/hashCode/toString)
      writeImports(writer, fields, validationImports);

      // Write record declaration
      writer.write("/**\n");
      writer.write(" * Record for {@link " + classElement.getQualifiedName() + "}\n");
      writer.write(" * Generated by Project Equilibrium\n");
      writer.write(" */\n");

      // Write record with its parameters
      writer.write("public record " + recordClassName + "(");
      writeRecordParametersWithValidation(writer, fields);
      writer.write(") {}\n");
    }
  }

  private void writeImports(
      Writer writer, List<VariableElement> fields, Set<String> validationImports)
      throws IOException {
    Set<String> imports =
        fields.stream()
            .map(field -> field.asType().toString())
            .map(GeneratorUtility::extractBaseType)
            .filter(type -> type.contains("."))
            .collect(java.util.stream.Collectors.toSet());

    // Add validation imports
    imports.addAll(validationImports);

    for (String importType : imports) {
      writer.write("import " + importType + ";\n");
    }
    writer.write("\n");
  }

  /** Writes record parameters with validation annotations. */
  private void writeRecordParametersWithValidation(Writer writer, List<VariableElement> fields)
      throws IOException {
    if (fields.isEmpty()) {
      return;
    }

    writer.write("\n");
    for (int i = 0; i < fields.size(); i++) {
      VariableElement field = fields.get(i);

      // Write validation annotations for this field
      validationEmitter.emitParameterAnnotations(writer, field, recordId);

      // Write the field type and name
      String fieldType = field.asType().toString();
      writer.write(fieldType + " " + field.getSimpleName());

      if (i < fields.size() - 1) {
        writer.write(",\n");
      } else {
        writer.write("\n");
      }
    }
  }
}
