package io.github.soulcodingmatt.equilibrium.processor.core;

import java.io.IOException;
import javax.annotation.processing.Filer;
import javax.lang.model.element.Element;
import javax.tools.FileObject;
import javax.tools.JavaFileManager.Location;
import javax.tools.JavaFileObject;

/**
 * Delegates to a {@link Filer} and counts successful {@link Filer#createSourceFile} calls (Java
 * sources generated by the processor).
 */
public final class EquilibriumFilerStats implements Filer {

  private final Filer delegate;
  private int generatedJavaSourceCount;

  public EquilibriumFilerStats(Filer delegate) {
    this.delegate = delegate;
  }

  /** The wrapped filer (e.g. for tests asserting delegation). */
  public Filer delegateFiler() {
    return delegate;
  }

  public int getGeneratedJavaSourceCount() {
    return generatedJavaSourceCount;
  }

  @Override
  public JavaFileObject createSourceFile(CharSequence name, Element... originatingElements)
      throws IOException {
    JavaFileObject out = delegate.createSourceFile(name, originatingElements);
    generatedJavaSourceCount++;
    return out;
  }

  @Override
  public JavaFileObject createClassFile(CharSequence name, Element... originatingElements)
      throws IOException {
    return delegate.createClassFile(name, originatingElements);
  }

  @Override
  public FileObject createResource(
      Location location,
      CharSequence pkg,
      CharSequence relativeName,
      Element... originatingElements)
      throws IOException {
    return delegate.createResource(location, pkg, relativeName, originatingElements);
  }

  @Override
  public FileObject getResource(Location location, CharSequence pkg, CharSequence relativeName)
      throws IOException {
    return delegate.getResource(location, pkg, relativeName);
  }
}
