package io.github.soulcodingmatt.equilibrium.processor.generation.vo;

import io.github.soulcodingmatt.equilibrium.experimental.validation.vo.ValidateVo;
import io.github.soulcodingmatt.equilibrium.processor.generation.emit.GeneratorUtility;
import io.github.soulcodingmatt.equilibrium.processor.generation.emit.GeneratorUtility.AccessorConfig;
import io.github.soulcodingmatt.equilibrium.processor.generation.emit.GeneratorUtility.ConstructorConfig;
import io.github.soulcodingmatt.equilibrium.processor.generation.emit.GeneratorUtility.FieldInclusionConfig;
import io.github.soulcodingmatt.equilibrium.processor.generation.emit.GeneratorUtility.GeneratorType;
import io.github.soulcodingmatt.equilibrium.processor.validation.codegen.ValidationSupport;
import java.io.IOException;
import java.io.Writer;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.annotation.processing.Filer;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.tools.JavaFileObject;

public class VoGenerator {
  private final TypeElement classElement;
  private final String packageName;
  private final String voClassName;
  private final Set<String> ignoredFields;
  private final boolean generateSetters;
  private final Filer filer;
  private final int voId;

  public VoGenerator(
      TypeElement classElement,
      String packageName,
      String voClassName,
      Set<String> ignoredFields,
      boolean generateSetters,
      int voId,
      Filer filer) {
    this.classElement = classElement;
    this.packageName = packageName;
    this.voClassName = voClassName;
    this.ignoredFields = ignoredFields != null ? ignoredFields : new HashSet<>();
    this.generateSetters = generateSetters;
    this.filer = filer;
    this.voId = voId;
  }

  public void generate() throws IOException {
    // Create field inclusion configuration
    FieldInclusionConfig fieldConfig =
        new FieldInclusionConfig(GeneratorType.VO, ignoredFields, voId);

    // Get all fields that should be included in the Value Object
    List<VariableElement> fields = GeneratorUtility.getIncludedFields(classElement, fieldConfig);

    // Collect validation imports
    Set<String> validationImports = ValidationSupport.collectVoValidationImports(fields, voId);

    // Create or update the Value Object file
    JavaFileObject sourceFile =
        filer.createSourceFile(packageName + "." + voClassName, classElement);

    try (Writer writer = sourceFile.openWriter()) {
      // Write package declaration
      writer.write("package " + packageName + ";\n\n");

      // Write imports
      GeneratorUtility.writeBasicImports(writer, fields);

      // Write validation imports
      for (String validationImport : validationImports) {
        writer.write("import " + validationImport + ";\n");
      }
      if (!validationImports.isEmpty()) {
        writer.write("\n");
      }

      // Write class declaration
      writer.write("/**\n");
      writer.write(" * Value Object for {@link " + classElement.getQualifiedName() + "}\n");
      writer.write(" * Generated by Project Equilibrium\n");
      writer.write(" */\n");
      writer.write("public class " + voClassName + " {\n\n");

      // Create constructor configuration
      ConstructorConfig constructorConfig = new ConstructorConfig(!generateSetters, null);

      // Write fields with validation annotations
      for (VariableElement field : fields) {
        // Write validation annotations for this field
        ValidateVo[] validateAnnotations = field.getAnnotationsByType(ValidateVo.class);
        for (ValidateVo validateAnnotation : validateAnnotations) {
          if (ValidationSupport.shouldApplyVoValidation(validateAnnotation, voId)) {
            ValidationSupport.writeTypeSafeVoValidations(writer, validateAnnotation);
          }
        }

        GeneratorUtility.writeField(writer, field, constructorConfig);
      }

      // Write constructor
      GeneratorUtility.writeConstructor(writer, fields, voClassName, constructorConfig);

      // Create accessor configuration
      AccessorConfig accessorConfig = new AccessorConfig(generateSetters, null);

      // Write getters and optionally setters
      for (VariableElement field : fields) {
        GeneratorUtility.writeAccessors(writer, field, accessorConfig);
      }

      // Write standard method overrides (always generated)
      GeneratorUtility.writeEquals(writer, fields, voClassName);
      GeneratorUtility.writeHashCode(writer, fields);
      GeneratorUtility.writeToString(writer, fields, voClassName);

      // Close class
      writer.write("}\n");
    }
  }
}
