package io.github.soulcodingmatt.equilibrium.processor.orchestration;

import com.google.auto.service.AutoService;
import com.sun.source.util.Trees;
import io.github.soulcodingmatt.equilibrium.annotations.dto.GenerateDto;
import io.github.soulcodingmatt.equilibrium.annotations.dto.GenerateDtos;
import io.github.soulcodingmatt.equilibrium.annotations.record.GenerateRecord;
import io.github.soulcodingmatt.equilibrium.annotations.record.GenerateRecords;
import io.github.soulcodingmatt.equilibrium.annotations.vo.GenerateVo;
import io.github.soulcodingmatt.equilibrium.annotations.vo.GenerateVos;
import io.github.soulcodingmatt.equilibrium.processor.config.EquilibriumConfig;
import io.github.soulcodingmatt.equilibrium.processor.generation.dto.DtoGenerator;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;
import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;

@AutoService(Processor.class)
@SupportedAnnotationTypes({
  "io.github.soulcodingmatt.equilibrium.annotations.dto.DtoBuilderDefault",
  "io.github.soulcodingmatt.equilibrium.annotations.dto.GenerateDto",
  "io.github.soulcodingmatt.equilibrium.annotations.dto.GenerateDtos",
  "io.github.soulcodingmatt.equilibrium.annotations.dto.IgnoreDto",
  "io.github.soulcodingmatt.equilibrium.experimental.validation.dto.ValidateDto",
  "io.github.soulcodingmatt.equilibrium.experimental.validation.dto.ValidateDtos",
  "io.github.soulcodingmatt.equilibrium.annotations.dto.NestedMapping",
  "io.github.soulcodingmatt.equilibrium.annotations.dto.NestedMappings",
  "io.github.soulcodingmatt.equilibrium.annotations.dto.NestedDtoMapping",
  "io.github.soulcodingmatt.equilibrium.annotations.dto.NestedDtoMappings",
  "io.github.soulcodingmatt.equilibrium.annotations.record.GenerateRecord",
  "io.github.soulcodingmatt.equilibrium.annotations.record.GenerateRecords",
  "io.github.soulcodingmatt.equilibrium.annotations.record.IgnoreRecord",
  "io.github.soulcodingmatt.equilibrium.experimental.validation.record.ValidateRecord",
  "io.github.soulcodingmatt.equilibrium.experimental.validation.record.ValidateRecords",
  "io.github.soulcodingmatt.equilibrium.annotations.vo.GenerateVo",
  "io.github.soulcodingmatt.equilibrium.annotations.vo.GenerateVos",
  "io.github.soulcodingmatt.equilibrium.annotations.vo.IgnoreVo",
  "io.github.soulcodingmatt.equilibrium.experimental.validation.vo.ValidateVo",
  "io.github.soulcodingmatt.equilibrium.experimental.validation.vo.ValidateVos",
  "io.github.soulcodingmatt.equilibrium.annotations.common.IgnoreAll",
  // Jakarta Bean Validation annotations generated by this processor
  "jakarta.validation.constraints.NotNull",
  "jakarta.validation.constraints.NotBlank",
  "jakarta.validation.constraints.NotEmpty",
  "jakarta.validation.constraints.Size",
  "jakarta.validation.constraints.Min",
  "jakarta.validation.constraints.Max",
  "jakarta.validation.constraints.Email",
  "jakarta.validation.constraints.Pattern",
  "jakarta.validation.constraints.Positive",
  "jakarta.validation.constraints.PositiveOrZero",
  "jakarta.validation.constraints.Negative",
  "jakarta.validation.constraints.NegativeOrZero",
  "jakarta.validation.constraints.Digits",
  "jakarta.validation.constraints.Past",
  "jakarta.validation.constraints.Future",
  "jakarta.validation.constraints.PastOrPresent",
  "jakarta.validation.constraints.FutureOrPresent"
})
@SupportedSourceVersion(SourceVersion.RELEASE_21)
@SupportedOptions({
  "equilibrium.dto.package",
  "equilibrium.dto.postfix",
  "equilibrium.record.package",
  "equilibrium.record.postfix",
  "equilibrium.vo.package",
  "equilibrium.vo.postfix",
  "equilibrium.groupId",
  "equilibrium.artifactId",
  "equilibrium.banner",
  "equilibrium.banner.color"
})
public class EquilibriumProcessor extends AbstractProcessor {

  private final Set<String> processedElements = new HashSet<>();

  @Override
  public SourceVersion getSupportedSourceVersion() {
    return SourceVersion.latest();
  }

  private Messager messager;
  private EquilibriumMessagerStats messagerStats;
  private EquilibriumFilerStats filerStats;
  private boolean buildBannerEnabled;
  private boolean bannerAnsiColors;
  private boolean emittedGenerationNotes;

  private DtoGenerationOrchestrator dtoOrchestrator;
  private RecordGenerationOrchestrator recordOrchestrator;
  private VoGenerationOrchestrator voOrchestrator;
  private ValidationAnnotationOrchestrator validationOrchestrator;

  @Override
  public synchronized void init(ProcessingEnvironment processingEnv) {
    super.init(processingEnv);
    messagerStats = new EquilibriumMessagerStats(processingEnv.getMessager());
    messager = messagerStats;
    Filer rawFiler = processingEnv.getFiler();
    Filer filer;
    if (rawFiler != null) {
      filerStats = new EquilibriumFilerStats(rawFiler);
      filer = filerStats;
    } else {
      filerStats = null;
      filer = null;
    }
    processedElements.clear();
    DtoGenerator.clearRegistry();
    buildBannerEnabled = isBuildBannerEnabled(processingEnv);
    bannerAnsiColors = isBannerAnsiColorsEnabled(processingEnv);
    emittedGenerationNotes = false;
    if (buildBannerEnabled) {
      EquilibriumBuildBanner.print(messager);
    }
    EquilibriumConfig config = new EquilibriumConfig(processingEnv);
    Trees trees = null;
    try {
      trees = Trees.instance(processingEnv);
    } catch (IllegalArgumentException ex) {
      // Trees may be unavailable in some environments — trees stays null
    }

    DiagnosticReporter reporter = createReporter();
    dtoOrchestrator = new DtoGenerationOrchestrator(config, reporter, filer, trees, messager);
    recordOrchestrator = new RecordGenerationOrchestrator(config, reporter, filer);
    voOrchestrator = new VoGenerationOrchestrator(config, reporter, filer);
    validationOrchestrator = new ValidationAnnotationOrchestrator(reporter);
  }

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
    if (roundEnv.processingOver()) {
      printGenerationSummaryOnLastRoundIfEnabled();
      return false;
    }
    return processModelRound(annotations, roundEnv);
  }

  private void printGenerationSummaryOnLastRoundIfEnabled() {
    if (buildBannerEnabled && shouldPrintGenerationSummary()) {
      int generatedFiles = filerStats != null ? filerStats.getGeneratedJavaSourceCount() : 0;
      EquilibriumBuildBanner.printGenerationSummary(
          messager,
          processedElements.size(),
          generatedFiles,
          messagerStats.getErrorCount(),
          messagerStats.getWarningCount(),
          bannerAnsiColors);
    }
  }

  private boolean processModelRound(
      Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
    boolean hasEquilibriumAnnotations =
        annotations.stream()
            .map(TypeElement::getQualifiedName)
            .map(Object::toString)
            .anyMatch(name -> name.startsWith("io.github.soulcodingmatt.equilibrium.annotations"));

    boolean hasJakartaValidationAnnotations =
        annotations.stream()
            .map(TypeElement::getQualifiedName)
            .map(Object::toString)
            .anyMatch(name -> name.startsWith("jakarta.validation.constraints"));

    if (hasJakartaValidationAnnotations && !hasEquilibriumAnnotations) {
      return true;
    }

    try {
      Set<TypeElement> validElements = getValidClassElements(roundEnv);
      if (validElements.isEmpty()) {
        return false;
      }

      for (TypeElement typeElement : validElements) {
        if (!validationOrchestrator.validateAll(typeElement)) {
          return false;
        }
      }

      preRegisterAllDtos(validElements);
      for (TypeElement typeElement : validElements) {
        processElement(typeElement);
      }
      return true;
    } catch (Exception e) {
      reportProcessingFailure(roundEnv, e);
      return false;
    }
  }

  private void reportProcessingFailure(RoundEnvironment roundEnv, Exception e) {
    Set<TypeElement> validElements = getValidClassElements(roundEnv);
    if (!validElements.isEmpty()) {
      TypeElement contextElement = validElements.iterator().next();
      error(
          contextElement,
          "Failed to process annotations: "
              + e.getMessage()
              + " ("
              + e.getClass().getSimpleName()
              + ")");
    } else {
      error(
          "Failed to process annotations: "
              + e.getMessage()
              + " ("
              + e.getClass().getSimpleName()
              + ")");
    }
  }

  private Set<TypeElement> getValidClassElements(RoundEnvironment roundEnv) {
    Set<Element> elements = new HashSet<>();
    elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateDto.class));
    elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateDtos.class));
    elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateRecord.class));
    elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateRecords.class));
    elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateVo.class));
    elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateVos.class));

    return elements.stream()
        .filter(this::isValidClassElement)
        .map(TypeElement.class::cast)
        .collect(Collectors.toSet());
  }

  private boolean isValidClassElement(Element element) {
    if (element.getKind() != ElementKind.CLASS) {
      error(element, "Annotations can only be applied to classes");
      return false;
    }
    return true;
  }

  private void processElement(TypeElement typeElement) {
    String qualifiedName = typeElement.getQualifiedName().toString();

    if (processedElements.contains(qualifiedName)) {
      return;
    }
    processedElements.add(qualifiedName);

    processGenerateDtos(typeElement);
    processGenerateRecords(typeElement);
    processGenerateVos(typeElement);
  }

  private void error(Element element, String message) {
    messager.printMessage(Diagnostic.Kind.ERROR, message, element);
  }

  private void error(String message) {
    messager.printMessage(Diagnostic.Kind.ERROR, message);
  }

  private void note(Element element, String message) {
    emittedGenerationNotes = true;
    messager.printMessage(Diagnostic.Kind.NOTE, message, element);
  }

  private boolean shouldPrintGenerationSummary() {
    return emittedGenerationNotes
        || !processedElements.isEmpty()
        || (filerStats != null && filerStats.getGeneratedJavaSourceCount() > 0)
        || messagerStats.getErrorCount() > 0
        || messagerStats.getWarningCount() > 0;
  }

  private void processGenerateDtos(TypeElement classElement) {
    dtoOrchestrator.processGenerateDtos(classElement);
  }

  private void processGenerateRecords(TypeElement classElement) {
    recordOrchestrator.processGenerateRecords(classElement);
  }

  private void processGenerateVos(TypeElement classElement) {
    voOrchestrator.processGenerateVos(classElement);
  }

  private void preRegisterAllDtos(Set<TypeElement> validElements) {
    dtoOrchestrator.preRegisterAllDtos(validElements);
  }

  private DiagnosticReporter createReporter() {
    return new DiagnosticReporter() {
      @Override
      public void note(Element element, String message) {
        EquilibriumProcessor.this.note(element, message);
      }

      @Override
      public void error(Element element, String message) {
        EquilibriumProcessor.this.error(element, message);
      }

      @Override
      public void error(String message) {
        EquilibriumProcessor.this.error(message);
      }

      @Override
      public void warning(Element element, String message) {
        messager.printMessage(Diagnostic.Kind.WARNING, message, element);
      }

      @Override
      public void warning(String message) {
        messager.printMessage(Diagnostic.Kind.WARNING, message);
      }
    };
  }

  private static boolean isBuildBannerEnabled(ProcessingEnvironment processingEnv) {
    String value = processingEnv.getOptions().get("equilibrium.banner");
    if (value == null) {
      return true;
    }
    return !"false".equalsIgnoreCase(value.trim());
  }

  private static boolean isBannerAnsiColorsEnabled(ProcessingEnvironment processingEnv) {
    String value = processingEnv.getOptions().get("equilibrium.banner.color");
    if (value == null) {
      return true;
    }
    return !"false".equalsIgnoreCase(value.trim());
  }
}
