package io.github.soulcodingmatt.equilibrium.processor;

import com.google.auto.service.AutoService;
import io.github.soulcodingmatt.equilibrium.annotations.dto.*;
import io.github.soulcodingmatt.equilibrium.annotations.record.GenerateRecord;
import io.github.soulcodingmatt.equilibrium.annotations.record.GenerateRecords;
import io.github.soulcodingmatt.equilibrium.annotations.record.IgnoreRecord;
import io.github.soulcodingmatt.equilibrium.annotations.vo.GenerateVo;
import io.github.soulcodingmatt.equilibrium.annotations.vo.GenerateVos;
import io.github.soulcodingmatt.equilibrium.annotations.vo.IgnoreVo;
import io.github.soulcodingmatt.equilibrium.processor.generator.DtoGenerator;
import io.github.soulcodingmatt.equilibrium.processor.generator.RecordGenerator;
import io.github.soulcodingmatt.equilibrium.processor.generator.VoGenerator;
import io.github.soulcodingmatt.equilibrium.processor.util.CustomObjectDetector;
import io.github.soulcodingmatt.equilibrium.processor.util.ValidationConflictUtil;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.tools.Diagnostic;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@AutoService(Processor.class)
@SupportedAnnotationTypes({
        "io.github.soulcodingmatt.equilibrium.annotations.dto.GenerateDto",
        "io.github.soulcodingmatt.equilibrium.annotations.dto.GenerateDtos",
        "io.github.soulcodingmatt.equilibrium.annotations.dto.IgnoreDto",
        "io.github.soulcodingmatt.equilibrium.annotations.dto.ValidateDto",
        "io.github.soulcodingmatt.equilibrium.annotations.dto.ValidateDtos",
        "io.github.soulcodingmatt.equilibrium.annotations.dto.NestedMapping",
        "io.github.soulcodingmatt.equilibrium.annotations.record.GenerateRecord",
        "io.github.soulcodingmatt.equilibrium.annotations.record.GenerateRecords",
        "io.github.soulcodingmatt.equilibrium.annotations.record.IgnoreRecord",
        "io.github.soulcodingmatt.equilibrium.annotations.vo.GenerateVo",
        "io.github.soulcodingmatt.equilibrium.annotations.vo.GenerateVos",
        "io.github.soulcodingmatt.equilibrium.annotations.vo.IgnoreVo",
        "io.github.soulcodingmatt.equilibrium.annotations.common.IgnoreAll",
        // Jakarta Bean Validation annotations generated by this processor
        "jakarta.validation.constraints.NotNull",
        "jakarta.validation.constraints.NotBlank",
        "jakarta.validation.constraints.NotEmpty",
        "jakarta.validation.constraints.Size",
        "jakarta.validation.constraints.Min",
        "jakarta.validation.constraints.Max",
        "jakarta.validation.constraints.Email",
        "jakarta.validation.constraints.Pattern",
        "jakarta.validation.constraints.Positive",
        "jakarta.validation.constraints.PositiveOrZero",
        "jakarta.validation.constraints.Negative",
        "jakarta.validation.constraints.NegativeOrZero",
        "jakarta.validation.constraints.Digits",
        "jakarta.validation.constraints.Past",
        "jakarta.validation.constraints.Future",
        "jakarta.validation.constraints.PastOrPresent",
        "jakarta.validation.constraints.FutureOrPresent"
})
@SupportedSourceVersion(SourceVersion.RELEASE_21)
@SupportedOptions({
        "equilibrium.dto.package",
        "equilibrium.dto.postfix",
        "equilibrium.record.package",
        "equilibrium.record.postfix",
        "equilibrium.vo.package",
        "equilibrium.vo.postfix"
})
public class EquilibriumProcessor extends AbstractProcessor {
    public static final String DUPLICATE_ID = "Duplicate ID ";
    public static final String DUPLICATES_WILL_BE_IGNORED = "' - duplicates will be ignored";
    public static final String RECORD = "Record";
    public static final String INVALID_FIELD_NAME_IN_IGNORE_LIST = "Invalid field name in ignore list: '";
    public static final String WILL_BE_SKIPPED = "' - will be skipped";
    private final Set<String> processedElements = new HashSet<>();

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latest();
    }

    private Filer filer;
    private Messager messager;
    private EquilibriumConfig config;
    private ValidationConflictUtil validationUtil;
    private CustomObjectDetector customObjectDetector;

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        filer = processingEnv.getFiler();
        messager = processingEnv.getMessager();
        config = new EquilibriumConfig(processingEnv);
        validationUtil = new ValidationConflictUtil(processingEnv.getTypeUtils());
        customObjectDetector = new CustomObjectDetector(processingEnv.getTypeUtils());
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        // If processing is over, we haven't claimed any new annotations
        if (roundEnv.processingOver()) {
            return false;
        }

        // Check if any of our Equilibrium annotations are present
        boolean hasEquilibriumAnnotations = annotations.stream()
                .map(TypeElement::getQualifiedName)
                .map(Object::toString)
                .anyMatch(name -> name.startsWith("io.github.soulcodingmatt.equilibrium.annotations"));

        // Check if any Jakarta validation annotations are present
        boolean hasJakartaValidationAnnotations = annotations.stream()
                .map(TypeElement::getQualifiedName)
                .map(Object::toString)
                .anyMatch(name -> name.startsWith("jakarta.validation.constraints"));

        // If we have Jakarta validation annotations but no Equilibrium annotations,
        // we should still claim the Jakarta annotations since we likely generated them
        if (hasJakartaValidationAnnotations && !hasEquilibriumAnnotations) {
            // Just claim the Jakarta validation annotations without processing
            return true;
        }

        // If no relevant annotations are present, don't claim anything
        if (!hasEquilibriumAnnotations && !hasJakartaValidationAnnotations) {
            return false;
        }

        try {
            // Get valid class elements that need processing
            Set<TypeElement> validElements = getValidClassElements(roundEnv);

            // If no valid elements found, don't claim the annotations
            if (validElements.isEmpty()) {
                return false;
            }

            // Validate ValidateDto annotations before processing
            for (TypeElement typeElement : validElements) {
                if (!validateValidateDtoAnnotations(typeElement)) {
                    // Validation failed, compilation errors already generated
                    return false;
                }
                
                // Validate NestedMapping annotations
                if (!validateNestedMappingAnnotations(typeElement)) {
                    // Validation failed, compilation errors already generated
                    return false;
                }
            }
            
            // FIRST PASS: Pre-register all DTOs that will be generated
            preRegisterAllDtos(validElements);
            
            // SECOND PASS: Process each valid element normally
            for (TypeElement typeElement : validElements) {
                processElement(typeElement);
            }

            // We've processed our annotations, so claim them
            // This includes both Equilibrium annotations and any Jakarta validation annotations
            // that we generate in the output DTOs
            return true;
        } catch (Exception e) {
            // Try to get the first valid element for better error context
            Set<TypeElement> validElements = getValidClassElements(roundEnv);
            if (!validElements.isEmpty()) {
                TypeElement contextElement = validElements.iterator().next();
                error(contextElement, "Failed to process annotations: " + e.getMessage() + " (" + e.getClass().getSimpleName() + ")");
            } else {
                error("Failed to process annotations: " + e.getMessage() + " (" + e.getClass().getSimpleName() + ")");
            }
            // On error, don't claim the annotations so other processors might handle them
            return false;
        }
    }

    private Set<TypeElement> getValidClassElements(RoundEnvironment roundEnv) {
        Set<Element> elements = new HashSet<>();
        elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateDto.class));
        elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateDtos.class));
        elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateRecord.class));
        elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateRecords.class));
        elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateVo.class));
        elements.addAll(roundEnv.getElementsAnnotatedWith(GenerateVos.class));

        return elements.stream()
                .filter(this::isValidClassElement)
                .map(TypeElement.class::cast)
                .collect(Collectors.toSet());
    }

    private boolean isValidClassElement(Element element) {
        if (element.getKind() != ElementKind.CLASS) {
            error(element, "Annotations can only be applied to classes");
            return false;
        }
        return true;
    }

    private void processElement(TypeElement typeElement) {
        String qualifiedName = typeElement.getQualifiedName().toString();

        // Skip if already processed
        if (processedElements.contains(qualifiedName)) {
            return;
        }
        processedElements.add(qualifiedName);

        // Process multiple DTO annotations
        processGenerateDtos(typeElement);

        // Process multiple Record annotations
        processGenerateRecords(typeElement);

        // Process multiple VO annotations
        processGenerateVos(typeElement);
    }

    private void processGenerateDtos(TypeElement classElement) {
        // Get all @GenerateDto annotations (handles both single and multiple annotations)
        GenerateDto[] dtoAnnotations = classElement.getAnnotationsByType(GenerateDto.class);
        
        if (dtoAnnotations.length == 0) {
            return; // No DTO annotations found
        }
        
        // Validate unique combinations of package and postfix
        if (!validateUniqueDtoCombinations(classElement, dtoAnnotations)) {
            return; // Validation failed, error already logged
        }
        
        // Collect all valid IDs from DTO annotations for orphaned ID validation
        Set<Integer> validDtoIds = new HashSet<>();
        for (GenerateDto annotation : dtoAnnotations) {
            int id = annotation.id();
            if (id != -1) {
                validDtoIds.add(id);
            }
        }
        
        // Validate @IgnoreDto annotations for duplicate IDs and orphaned ID references
        validateIgnoreDtoAnnotations(classElement, validDtoIds);
        
        // Process each DTO annotation
        for (GenerateDto annotation : dtoAnnotations) {
            processGenerateDto(classElement, annotation);
        }
    }

    private boolean validateUniqueDtoCombinations(TypeElement classElement, GenerateDto[] annotations) {
        Set<String> uniqueCombinations = new HashSet<>();
        Set<Integer> usedIds = new HashSet<>();
        
        for (GenerateDto annotation : annotations) {
            String packageName = config.validateAndGetPackage(annotation.pkg(), "DTO");
            String className;
            
            // Check if custom name is provided
            if (!annotation.name().isEmpty()) {
                className = annotation.name();
            } else {
                // Fall back to postfix-based naming
                String postfix = config.validateAndGetPostfix("", "DTO");
                className = classElement.getSimpleName() + postfix;
            }
            
            String combination = packageName + "." + className;
            
            if (!uniqueCombinations.add(combination)) {
                error(classElement, "Duplicate DTO configuration would generate the same class: " + combination);
                return false;
            }
            
            // Validate unique IDs (only if ID is explicitly set)
            int id = annotation.id();
            if (id != -1 && !usedIds.add(id)) {
                    error(classElement, "Duplicate DTO ID: " + id + ". Each @GenerateDto annotation must have a unique ID.");
                    return false;
                }

        }
        
        return true;
    }

    private void processGenerateDto(TypeElement classElement, GenerateDto annotation) {
        try {
            String packageName = config.validateAndGetPackage(annotation.pkg(), "DTO");
            String className;
            boolean useCustomName = !annotation.name().isEmpty();
            
            if (useCustomName) {
                className = annotation.name();
            } else {
                String postfix = config.validateAndGetPostfix("", "DTO");
                className = classElement.getSimpleName() + postfix;
            }
            
            // Process ignore field names array and validate each field name
            Set<String> ignoredFields = new HashSet<>();
            for (String fieldName : annotation.ignore()) {
                if (config.isValidFieldName(fieldName)) {
                    ignoredFields.add(fieldName);
                } else if (!fieldName.isEmpty()) {
                    // Log warning for invalid field names but continue processing
                    messager.printMessage(Diagnostic.Kind.WARNING, 
                        INVALID_FIELD_NAME_IN_IGNORE_LIST + fieldName + WILL_BE_SKIPPED,
                        classElement);
                }
            }
            
            boolean builder = annotation.builder();

            // Create and run the DTO generator
            int dtoId = annotation.id();
            DtoGenerator generator = new DtoGenerator(classElement, packageName, className, ignoredFields, builder, dtoId, filer, customObjectDetector, messager);
            generator.generate();

            note(classElement, "Generated DTO class: " + packageName + "." + className);
            
            // Register the generated DTO for import resolution
            DtoGenerator.registerGeneratedDto(className, packageName + "." + className);
        } catch (Exception e) {
            error(classElement, "Failed to generate DTO: " + e.getMessage() + " (" + e.getClass().getSimpleName() + ")");
        }
    }

    private void validateIgnoreDtoAnnotations(TypeElement classElement, Set<Integer> validDtoIds) {
        // Check all fields for @IgnoreDto annotations and validate their ids arrays
        classElement.getEnclosedElements().stream()
            .filter(e -> e.getKind() == ElementKind.FIELD)
            .map(VariableElement.class::cast)
            .forEach(field -> {
                IgnoreDto ignoreDtoAnnotation = field.getAnnotation(IgnoreDto.class);
                if (ignoreDtoAnnotation != null) {
                    int[] ids = ignoreDtoAnnotation.ids();
                    Set<Integer> uniqueIds = new HashSet<>();
                    for (int id : ids) {
                        if (!uniqueIds.add(id)) {
                            messager.printMessage(Diagnostic.Kind.WARNING,
                                DUPLICATE_ID + id + " in @IgnoreDto annotation for field '" +
                                field.getSimpleName() + DUPLICATES_WILL_BE_IGNORED, field);
                        } else if (!validDtoIds.isEmpty() && !validDtoIds.contains(id)) {
                            // Only check for orphaned IDs if there are actually IDs defined in @GenerateDto annotations
                            messager.printMessage(Diagnostic.Kind.WARNING,
                                "ID " + id + " in @IgnoreDto annotation for field '" + 
                                field.getSimpleName() + "' does not correspond to any @GenerateDto annotation ID", field);
                        }
                    }
                }
            });
    }

    private void processGenerateRecords(TypeElement classElement) {
        // Get all @GenerateRecord annotations (handles both single and multiple annotations)
        GenerateRecord[] recordAnnotations = classElement.getAnnotationsByType(GenerateRecord.class);
        
        if (recordAnnotations.length == 0) {
            return; // No Record annotations found
        }
        
        // Validate unique combinations of package and postfix
        if (!validateUniqueRecordCombinations(classElement, recordAnnotations)) {
            return; // Validation failed, error already logged
        }
        
        // Collect all valid IDs from Record annotations for orphaned ID validation
        Set<Integer> validRecordIds = new HashSet<>();
        for (GenerateRecord annotation : recordAnnotations) {
            int id = annotation.id();
            if (id != -1) {
                validRecordIds.add(id);
            }
        }
        
        // Validate @IgnoreRecord annotations for duplicate IDs and orphaned ID references
        validateIgnoreRecordAnnotations(classElement, validRecordIds);
        
        // Process each Record annotation
        for (GenerateRecord annotation : recordAnnotations) {
            processGenerateRecord(classElement, annotation);
        }
    }

    private boolean validateUniqueRecordCombinations(TypeElement classElement, GenerateRecord[] annotations) {
        Set<String> uniqueCombinations = new HashSet<>();
        Set<Integer> usedIds = new HashSet<>();
        
        for (GenerateRecord annotation : annotations) {
            String packageName = config.validateAndGetPackage(annotation.pkg(), RECORD);
            String className;
            
            // Check if custom name is provided
            if (!annotation.name().isEmpty()) {
                className = annotation.name();
            } else {
                // Fall back to postfix-based naming
                String postfix = config.validateAndGetPostfix("", RECORD);
                className = classElement.getSimpleName() + postfix;
            }
            
            String combination = packageName + "." + className;
            
            if (!uniqueCombinations.add(combination)) {
                error(classElement, "Duplicate Record configuration would generate the same class: " + combination);
                return false;
            }
            
            // Validate unique IDs (only if ID is explicitly set)
            int id = annotation.id();
            if (id != -1 && !usedIds.add(id)) {
                    error(classElement, "Duplicate Record ID: " + id + ". Each @GenerateRecord annotation must have a unique ID.");
                    return false;
                }

        }
        
        return true;
    }

    private void processGenerateRecord(TypeElement classElement, GenerateRecord annotation) {
        try {
            String packageName = config.validateAndGetPackage(annotation.pkg(), RECORD);
            String className;
            boolean useCustomName = !annotation.name().isEmpty();
            
            if (useCustomName) {
                className = annotation.name();
            } else {
                String postfix = config.validateAndGetPostfix("", RECORD);
                className = classElement.getSimpleName() + postfix;
            }
            
            // Process ignore field names array and validate each field name
            Set<String> ignoredFields = new HashSet<>();
            for (String fieldName : annotation.ignore()) {
                if (config.isValidFieldName(fieldName)) {
                    ignoredFields.add(fieldName);
                } else if (!fieldName.isEmpty()) {
                    // Log warning for invalid field names but continue processing
                    messager.printMessage(Diagnostic.Kind.WARNING, 
                        INVALID_FIELD_NAME_IN_IGNORE_LIST + fieldName + WILL_BE_SKIPPED,
                        classElement);
                }
            }
            
            // Create and run the Record generator
            int recordId = annotation.id();
            RecordGenerator generator = new RecordGenerator(classElement, packageName, className, ignoredFields, recordId, filer);
            generator.generate();

            note(classElement, "Generated Record class: " + packageName + "." + className);
        } catch (Exception e) {
            error(classElement, "Failed to generate Record: " + e.getMessage() + " (" + e.getClass().getSimpleName() + ")");
        }
    }

    private void validateIgnoreRecordAnnotations(TypeElement classElement, Set<Integer> validRecordIds) {
        // Check all fields for @IgnoreRecord annotations and validate their ids arrays
        classElement.getEnclosedElements().stream()
            .filter(e -> e.getKind() == ElementKind.FIELD)
            .map(VariableElement.class::cast)
            .forEach(field -> {
                IgnoreRecord ignoreRecordAnnotation = field.getAnnotation(IgnoreRecord.class);
                if (ignoreRecordAnnotation != null) {
                    int[] ids = ignoreRecordAnnotation.ids();
                    Set<Integer> uniqueIds = new HashSet<>();
                    for (int id : ids) {
                        if (!uniqueIds.add(id)) {
                            messager.printMessage(Diagnostic.Kind.WARNING,
                                DUPLICATE_ID + id + " in @IgnoreRecord annotation for field '" +
                                field.getSimpleName() + DUPLICATES_WILL_BE_IGNORED, field);
                        } else if (!validRecordIds.isEmpty() && !validRecordIds.contains(id)) {
                            // Only check for orphaned IDs if there are actually IDs defined in @GenerateRecord annotations
                            messager.printMessage(Diagnostic.Kind.WARNING,
                                "ID " + id + " in @IgnoreRecord annotation for field '" + 
                                field.getSimpleName() + "' does not correspond to any @GenerateRecord annotation ID", field);
                        }
                    }
                }
            });
    }

    private void processGenerateVos(TypeElement classElement) {
        // Get all @GenerateVo annotations (handles both single and multiple annotations)
        GenerateVo[] voAnnotations = classElement.getAnnotationsByType(GenerateVo.class);
        
        if (voAnnotations.length == 0) {
            return; // No VO annotations found
        }
        
        // Validate unique combinations of package and postfix
        if (!validateUniqueVoCombinations(classElement, voAnnotations)) {
            return; // Validation failed, error already logged
        }
        
        // Collect all valid IDs from VO annotations for orphaned ID validation
        Set<Integer> validVoIds = new HashSet<>();
        for (GenerateVo annotation : voAnnotations) {
            int id = annotation.id();
            if (id != -1) {
                validVoIds.add(id);
            }
        }
        
        // Validate @IgnoreVo annotations for duplicate IDs and orphaned ID references
        validateIgnoreVoAnnotations(classElement, validVoIds);
        
        // Process each VO annotation
        for (GenerateVo annotation : voAnnotations) {
            processGenerateVo(classElement, annotation);
        }
    }

    private boolean validateUniqueVoCombinations(TypeElement classElement, GenerateVo[] annotations) {
        Set<String> uniqueCombinations = new HashSet<>();
        Set<Integer> usedIds = new HashSet<>();
        
        for (GenerateVo annotation : annotations) {
            String packageName = config.validateAndGetPackage(annotation.pkg(), "VO");
            String className;
            
            // Check if custom name is provided
            if (!annotation.name().isEmpty()) {
                className = annotation.name();
            } else {
                // Fall back to postfix-based naming
                String postfix = config.validateAndGetPostfix("", "VO");
                className = classElement.getSimpleName() + postfix;
            }
            
            String combination = packageName + "." + className;
            
            if (!uniqueCombinations.add(combination)) {
                error(classElement, "Duplicate VO configuration would generate the same class: " + combination);
                return false;
            }
            
            // Validate unique IDs (only if ID is explicitly set)
            int id = annotation.id();
            if (id != -1 && !usedIds.add(id)) {
                    error(classElement, "Duplicate VO ID: " + id + ". Each @GenerateVo annotation must have a unique ID.");
                    return false;
                }

        }
        
        return true;
    }

    private void processGenerateVo(TypeElement classElement, GenerateVo annotation) {
        try {
            String packageName = config.validateAndGetPackage(annotation.pkg(), "VO");
            String className;
            boolean useCustomName = !annotation.name().isEmpty();
            
            if (useCustomName) {
                className = annotation.name();
            } else {
                String postfix = config.validateAndGetPostfix("", "VO");
                className = classElement.getSimpleName() + postfix;
            }
            
            // Process ignore field names array and validate each field name
            Set<String> ignoredFields = new HashSet<>();
            for (String fieldName : annotation.ignore()) {
                if (config.isValidFieldName(fieldName)) {
                    ignoredFields.add(fieldName);
                } else if (!fieldName.isEmpty()) {
                    // Log warning for invalid field names but continue processing
                    messager.printMessage(Diagnostic.Kind.WARNING, 
                        INVALID_FIELD_NAME_IN_IGNORE_LIST + fieldName + WILL_BE_SKIPPED,
                        classElement);
                }
            }
            
            boolean generateSetter = annotation.setters();

            // Create and run the Value Object generator
            int voId = annotation.id();
            VoGenerator generator = new VoGenerator(classElement, packageName, className, 
                                                  ignoredFields, generateSetter, voId, filer);
            generator.generate();

            note(classElement, "Generated Value Object class: " + packageName + "." + className);
        } catch (Exception e) {
            error(classElement, "Failed to generate Value Object: " + e.getMessage() + " (" + e.getClass().getSimpleName() + ")");
        }
    }

    /**
     * Pre-registers all DTOs that will be generated to enable cross-references during generation.
     */
    private void preRegisterAllDtos(Set<TypeElement> validElements) {
        for (TypeElement typeElement : validElements) {
            // Get all @GenerateDto annotations for this class
            GenerateDto[] dtoAnnotations = typeElement.getAnnotationsByType(GenerateDto.class);
            
            for (GenerateDto annotation : dtoAnnotations) {
                try {
                    String packageName = config.validateAndGetPackage(annotation.pkg(), "DTO");
                    String className;
                    
                    if (!annotation.name().isEmpty()) {
                        className = annotation.name();
                    } else {
                        String postfix = config.validateAndGetPostfix("", "DTO");
                        className = typeElement.getSimpleName() + postfix;
                    }
                    
                    String fullQualifiedName = packageName + "." + className;
                    
                    // Pre-register this DTO
                    DtoGenerator.registerGeneratedDto(className, fullQualifiedName);
                    
                    messager.printMessage(Diagnostic.Kind.NOTE, 
                        "DEBUG: Pre-registered DTO: " + className + " -> " + fullQualifiedName);
                        
                } catch (Exception e) {
                    // Continue with other DTOs if one fails
                    messager.printMessage(Diagnostic.Kind.WARNING, 
                        "Failed to pre-register DTO from " + typeElement.getSimpleName() + ": " + e.getMessage());
                }
            }
        }
    }

    private void validateIgnoreVoAnnotations(TypeElement classElement, Set<Integer> validVoIds) {
        // Check all fields for @IgnoreVo annotations and validate their ids arrays
        classElement.getEnclosedElements().stream()
            .filter(e -> e.getKind() == ElementKind.FIELD)
            .map(VariableElement.class::cast)
            .forEach(field -> {
                IgnoreVo ignoreVoAnnotation = field.getAnnotation(IgnoreVo.class);
                if (ignoreVoAnnotation != null) {
                    int[] ids = ignoreVoAnnotation.ids();
                    Set<Integer> uniqueIds = new HashSet<>();
                    for (int id : ids) {
                        if (!uniqueIds.add(id)) {
                            messager.printMessage(Diagnostic.Kind.WARNING,
                                DUPLICATE_ID + id + " in @IgnoreVo annotation for field '" +
                                field.getSimpleName() + DUPLICATES_WILL_BE_IGNORED, field);
                        } else if (!validVoIds.isEmpty() && !validVoIds.contains(id)) {
                            // Only check for orphaned IDs if there are actually IDs defined in @GenerateVo annotations
                            messager.printMessage(Diagnostic.Kind.WARNING,
                                "ID " + id + " in @IgnoreVo annotation for field '" + 
                                field.getSimpleName() + "' does not correspond to any @GenerateVo annotation ID", field);
                        }
                    }
                }
            });
    }
    
    /**
     * Validates all ValidateDto annotations in a class for type compatibility and logical conflicts.
     * 
     * @param classElement the class to validate
     * @return true if validation passes, false if there are errors
     */
    private boolean validateValidateDtoAnnotations(TypeElement classElement) {
        boolean hasErrors = false;
        
        // Check all fields for ValidateDto annotations
        for (Element element : classElement.getEnclosedElements()) {
            if (element.getKind() == ElementKind.FIELD) {
                VariableElement field = (VariableElement) element;
                
                // Get all ValidateDto annotations on this field (handles both single and repeatable)
                ValidateDto[] validateDtoAnnotations = field.getAnnotationsByType(ValidateDto.class);
                
                if (validateDtoAnnotations.length > 0) {
                    // Validate the field
                    List<String> errors = validationUtil.validateField(field, validateDtoAnnotations);
                    
                    // Report any errors
                    for (String errorMessage : errors) {
                        error(field, errorMessage);
                        hasErrors = true;
                    }
                }
            }
        }
        
        return !hasErrors;
    }
    
    /**
     * Validates all NestedMapping annotations in a class for proper usage and conflicts.
     * 
     * @param classElement the class to validate
     * @return true if validation passes, false if there are errors
     */
    private boolean validateNestedMappingAnnotations(TypeElement classElement) {
        boolean hasErrors = false;
        
        // Check all fields for NestedMapping annotations
        for (Element element : classElement.getEnclosedElements()) {
            if (element.getKind() == ElementKind.FIELD) {
                VariableElement field = (VariableElement) element;
                
                // Get NestedMapping annotation on this field
                NestedMapping nestedMapping = field.getAnnotation(NestedMapping.class);
                
                if (nestedMapping != null) {
                    // Basic validation - the DTO class reference validation
                    // will happen naturally during code generation if the class doesn't exist
                    // No complex validation needed with simplified single-annotation approach
                }
            }
        }
        
        return !hasErrors;
    }
    


    private void error(Element element, String message) {
        messager.printMessage(Diagnostic.Kind.ERROR, message, element);
    }

    private void error(String message) {
        messager.printMessage(Diagnostic.Kind.ERROR, message);
    }

    private void note(Element element, String message) {
        messager.printMessage(Diagnostic.Kind.NOTE, message, element);
    }
}
